Applying apache license and adding license header on source files
bcwaldon/klondike pull request #48
Opened 2016-09-20 22:32 UTC by s26mehta

All the builds on wercker build without error

2016-09-20 22:37 UTC, bcwaldon commented
@s26mehta we don't want to touch any of the vendored code (anything with vendor/ in the path)

2016-09-20 23:02 UTC, s26mehta commented
@bcwaldon okay I have unedited vendor code.

2016-09-26 17:18 UTC, bcwaldon commented on group_vars/all
> +kube_datadog_image: quay.io/bcwaldon/kube-datadog:d79a29a4839188c7714fd4e6c6fa731f1aec50f6f
added an `f` to the end of this line, is that necessary?

2016-09-26 17:19 UTC, bcwaldon requested changes
Please revert the changes to the files in `roles/defunctzombie.coreos-bootstrap/`, as this is not planet code.

2016-09-26 18:46 UTC, s26mehta commented
Fixed both

2016-10-24 19:17 UTC, bcwaldon approved these changes

2016-10-24 19:17 UTC, bcwaldon commented
Made the remaining changes. Waiting for wercker sign-off

2016-10-24 19:18 UTC, merged